#!/usr/bin/env python3
"""C1v7 estimator for E2 loop L1f Phase B.

The sealed v4 estimator is imported read-only.  This revision freezes the
complete declared anchor surface before preparation, classifies every residual
against the sealed two-tier honest envelope, applies exact path hard blocks for
Tier B, and applies candidate-count-independent per-signal floors for Tier A.
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import importlib.util
import io
import json
import math
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Mapping, Sequence


sys.dont_write_bytecode = True

V4_PATH = Path(
    r"D:\dev\99_tools\autocad-sdk-router\tools\e2\cells\feyerabend_c1_v4.py"
)
REVISION = "c1v7_two_tier_frozen_surface_non_dilution"
MIN_HANDLES_NON_NONE = 2
MIN_HANDLES_HIGH = 3
SEVERE_DISTANCE_TAU = 3.5
HONEST_RATIO_ROUNDOFF_MAX_TAU = 1.4563237239633405e-13
O2_STALE_MAX_TAU = 2.1594622082423
O2_TYPE_TO_GRID_MAX_TAU = 0.5
TIER_A_MIN_PENALTY = 0.05
TIER_A_MAX_PENALTY = 0.25
GEOMETRY_REL_TOLERANCE = 1e-12
GEOMETRY_ABS_TOLERANCE = 1e-9

CURRENT_MINIMUM_DECLARED_FIELDS = (
    "anchor_factory_revision",
    "anchor_type",
    "display_unit",
    "display_value",
    "handle",
    "p0",
    "p1",
    "raw_span",
    "region",
    "text_height",
    "weight",
)

# These keys are generated by adversarial harnesses and were never part of the
# estimator's declared anchor contract.  Every other present key is frozen and
# inventoried, including source_span_id and future declared fields.
NON_ESTIMATOR_HARNESS_METADATA_FIELDS = frozenset(
    {"diagnostic_mutation", "suffix_removed", "text_override"}
)

DETECTION_RULE_ORDER = (
    "declared_field_inventory",
    "declared_field_type_and_presence",
    "raw_span_equals_euclidean_geometry",
    "source_handle_type_conflict",
    "source_handle_ratio_conflict",
    "source_handle_span_conflict",
    "mixed_estimator_ratio_space_trace",
    "ratio_missing_or_ambiguous_declaration",
    "grid_positive_display_contradiction",
    "annotation_scale_unregistered",
    "ratio_severe_distance",
    "span_severe_distance",
    "ratio_unregistered_or_envelope_exceeding_residual",
    "span_unregistered_or_envelope_exceeding_residual",
    "honest_corpus_coherent_ratio_roundoff",
    "O2_class_moderate_display_stale",
    "O2_class_type_to_grid_display_residual",
    "ratio_absent_GRID_neutrality",
)

NON_DILUTION_FORMULA = (
    "q_ratio=Q_clean_support*product_s(1-floor_s); "
    "q_reference=Q_clean_span_support*product_ratio_s(1-floor_s)*"
    "product_span_s(1-floor_s); floors are per suspicious signal and contain "
    "no candidate-count denominator; Tier B affected paths are exactly 0/NONE"
)
BOUNDARY_BEHAVIOR = (
    "The O2 Tier-A floor is 0.05+0.20*(d/L)^2 on its sealed interval, "
    "so the value and both one-sided limits agree at d=tau; Tier-B hard "
    "classes use the separately sealed closed-world boundary."
)


def _load_module(name: str, path: Path) -> Any:
    if not path.is_file():
        raise FileNotFoundError(path)
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise ImportError(path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


V4 = _load_module("loop_l1f_v4_readonly", V4_PATH)
V3 = V4.V3
ORIGINAL = V4.ORIGINAL
V2 = V4.V2

for _name in (
    "SCALES",
    "CONFIDENCE_LEVELS",
    "CORRUPTIONS",
    "RANSAC_LOG_TOLERANCE",
    "HUBER_DELTA",
    "HIGH_CONFIDENCE_THRESHOLD",
    "CONSENSUS_THRESHOLD",
    "ACCURACY_RELATIVE_ERROR",
    "EPSILON",
    "BASE_WEIGHTS",
    "UNIT_TO_MM",
    "SCORE_BINS",
    "PROPERTY_SEED",
    "PROPERTY_CASES",
    "STATUS_RANK",
    "TRACKED_FIELDS",
    "PROPERTY_FAMILIES",
    "L1B_SCENE_DIR",
    "V1_SCENE_DIR",
    "V1_COUNTEREXAMPLE_SCENE",
    "POSITIONS",
    "canonical_bytes",
    "canonical_sha256",
    "sha256_file",
    "finite_float",
    "round_key",
    "scale_token",
    "weighted_median",
    "weighted_log_mad",
    "huber_location",
    "geometric_span",
    "midpoint",
    "canonical_anchor_key",
    "prepare_anchors",
    "spatial_bin_count",
    "maximum_consensus",
    "assigned_corruption",
    "deterministic_index",
    "apply_corruption",
    "permute_pair_labels",
    "GuardedScene",
    "exact_fixture",
    "relative_error",
    "log_error",
    "numeric_distribution",
    "summarize_rows",
    "score_bin_for",
    "transition_counter",
    "corruption_summary",
    "aggregate_results",
    "randomized_corruption",
    "_ratio_indices",
    "_make_anchor",
):
    globals()[_name] = getattr(V4, _name)


def _canonical_digest(value: Any) -> str:
    return hashlib.sha256(canonical_bytes(value)).hexdigest()


def _finite(value: Any) -> float | None:
    try:
        number = float(value)
    except (TypeError, ValueError, OverflowError):
        return None
    return number if math.isfinite(number) else None


def _point(value: Any) -> tuple[float, float] | None:
    if not isinstance(value, (list, tuple)) or len(value) < 2:
        return None
    x = _finite(value[0])
    y = _finite(value[1])
    return None if x is None or y is None else (x, y)


def _geometry_span(record: Mapping[str, Any]) -> float | None:
    p0 = _point(record.get("p0"))
    p1 = _point(record.get("p1"))
    if p0 is None or p1 is None:
        return None
    value = math.hypot(p1[0] - p0[0], p1[1] - p0[1])
    return value if math.isfinite(value) and value > EPSILON else None


def estimator_input_surface(
    raw_anchors: Sequence[Mapping[str, Any]],
) -> list[dict[str, Any]]:
    """Freeze every declared estimator field before canonicalization.

    Unknown present fields are retained automatically.  Only the three known
    harness-history keys, which are not estimator declarations, are excluded.
    """
    surface: list[dict[str, Any]] = []
    for index, anchor in enumerate(raw_anchors):
        if not isinstance(anchor, Mapping):
            surface.append(
                {
                    "__invalid_record_index__": index,
                    "__invalid_record_type__": type(anchor).__name__,
                    "__invalid_record_repr__": repr(anchor),
                }
            )
            continue
        surface.append(
            {
                str(key): copy.deepcopy(value)
                for key, value in anchor.items()
                if str(key) not in NON_ESTIMATOR_HARNESS_METADATA_FIELDS
            }
        )
    return surface


def _tier_a_floor(distance_tau: float, limit_tau: float) -> float:
    scaled = min(1.0, max(0.0, float(distance_tau) / float(limit_tau)))
    return float(TIER_A_MIN_PENALTY + (TIER_A_MAX_PENALTY - TIER_A_MIN_PENALTY) * scaled * scaled)


def _ratio_entry(record: Mapping[str, Any], geometry: float) -> dict[str, Any] | None:
    if str(record.get("anchor_type", "")).upper() not in ("DIM", "TEXT"):
        return None
    display = _finite(record.get("display_value"))
    if display is None or display <= 0.0:
        return None
    unit = str(record.get("display_unit", "UNKNOWN")).upper()
    if unit in UNIT_TO_MM:
        space = "z_mm"
        normalized = display * float(UNIT_TO_MM[unit])
    else:
        space = "z_raw"
        normalized = display
    weight = _finite(record.get("weight"))
    if weight is None or weight <= 0.0:
        weight = float(BASE_WEIGHTS.get(str(record.get("anchor_type", "")).upper(), 1.0))
    return {
        **copy.deepcopy(dict(record)),
        "handle": str(record.get("handle", "")),
        "raw_span": float(geometry),
        "ratio_space": space,
        "normalized_display": float(normalized),
        "log_ratio": math.log(float(normalized) / float(geometry)),
        "weight": float(weight),
    }


def _span_entry(record: Mapping[str, Any], geometry: float) -> dict[str, Any]:
    weight = _finite(record.get("weight"))
    anchor_type = str(record.get("anchor_type", "")).upper()
    if weight is None or weight <= 0.0:
        weight = float(BASE_WEIGHTS.get(anchor_type, 1.0))
    return {
        **copy.deepcopy(dict(record)),
        "handle": str(record.get("handle", "")),
        "raw_span": float(geometry),
        "log_span": math.log(float(geometry)),
        "weight": float(weight),
    }


def _select_consensus(
    records: Sequence[Mapping[str, Any]], value_key: str, *, spaces: bool
) -> tuple[dict[str, Any] | None, list[dict[str, Any]]]:
    return V3._select_consensus(records, value_key, spaces=spaces)


def analyze_frozen_surface(
    raw_anchors: Sequence[Mapping[str, Any]],
) -> dict[str, Any]:
    """Adjudicate the complete pre-canonicalization surface."""
    surface = estimator_input_surface(raw_anchors)
    field_counts: Counter[str] = Counter()
    minimum_presence = Counter({field: 0 for field in CURRENT_MINIMUM_DECLARED_FIELDS})
    invalid_rows: list[dict[str, Any]] = []
    geometry_mismatches: list[dict[str, Any]] = []
    grid_display: list[dict[str, Any]] = []
    annotation_rows: list[dict[str, Any]] = []
    ratio_missing: list[dict[str, Any]] = []
    ratio_absent_grids: list[str] = []
    by_handle: dict[str, list[dict[str, Any]]] = defaultdict(list)
    geometry_by_index: dict[int, float] = {}

    tier_a: list[dict[str, Any]] = []
    tier_b: list[dict[str, Any]] = []

    def add_b(kind: str, paths: Sequence[str], measurement: Mapping[str, Any]) -> None:
        tier_b.append(
            {
                "signal_kind": kind,
                "tier": "B",
                "affected_paths": sorted(set(map(str, paths))),
                "measurement": copy.deepcopy(dict(measurement)),
            }
        )

    def add_a(
        kind: str,
        paths: Sequence[str],
        measurement: Mapping[str, Any],
        *,
        limit_tau: float,
        envelope_entry: str,
    ) -> None:
        distance = float(measurement["distance_tau"])
        tier_a.append(
            {
                "signal_kind": kind,
                "tier": "A",
                "affected_paths": sorted(set(map(str, paths))),
                "measurement": copy.deepcopy(dict(measurement)),
                "sealed_limit_tau": float(limit_tau),
                "sealed_envelope_entry": envelope_entry,
                "penalty_floor": _tier_a_floor(distance, limit_tau),
            }
        )

    for index, record in enumerate(surface):
        for field in record:
            field_counts[field] += 1
            if field in minimum_presence:
                minimum_presence[field] += 1
        if "__invalid_record_type__" in record:
            invalid_rows.append({"index": index, "reason": "record_not_mapping"})
            continue
        handle = record.get("handle")
        anchor_type = str(record.get("anchor_type", "")).upper()
        p0 = _point(record.get("p0"))
        p1 = _point(record.get("p1"))
        geometry = _geometry_span(record)
        raw_span = _finite(record.get("raw_span"))
        weight = _finite(record.get("weight"))
        reasons: list[str] = []
        if not isinstance(handle, str) or not handle:
            reasons.append("invalid_handle")
        if anchor_type not in BASE_WEIGHTS:
            reasons.append("unsupported_anchor_type")
        if p0 is None or p1 is None or geometry is None:
            reasons.append("invalid_geometry")
        if raw_span is None or raw_span <= 0.0:
            reasons.append("invalid_declared_raw_span")
        if "region" not in record:
            reasons.append("missing_region")
        if weight is None or weight <= 0.0:
            reasons.append("missing_or_invalid_weight")
        if reasons:
            invalid_rows.append(
                {"index": index, "handle": str(handle), "reasons": reasons}
            )
            continue
        assert geometry is not None and raw_span is not None
        geometry_by_index[index] = geometry
        if not math.isclose(
            raw_span,
            geometry,
            rel_tol=GEOMETRY_REL_TOLERANCE,
            abs_tol=GEOMETRY_ABS_TOLERANCE,
        ):
            geometry_mismatches.append(
                {
                    "index": index,
                    "handle": str(handle),
                    "declared_raw_span": raw_span,
                    "euclidean_geometry_span": geometry,
                    "absolute_delta": abs(raw_span - geometry),
                    "relative_delta": abs(raw_span - geometry) / max(geometry, EPSILON),
                }
            )
        display = _finite(record.get("display_value"))
        if anchor_type == "GRID":
            if display is not None and display > 0.0:
                grid_display.append(
                    {"index": index, "handle": str(handle), "display_value": display}
                )
            else:
                ratio_absent_grids.append(str(handle))
        if anchor_type in ("DIM", "TEXT") and (display is None or display <= 0.0):
            ratio_missing.append(
                {"index": index, "handle": str(handle), "display_value": record.get("display_value")}
            )
        text_height = _finite(record.get("text_height"))
        if text_height is not None and text_height > 0.0 and geometry / text_height < 10.0:
            annotation_rows.append(
                {
                    "index": index,
                    "handle": str(handle),
                    "geometry_span": geometry,
                    "text_height": text_height,
                    "span_to_text_height": geometry / text_height,
                }
            )
        by_handle[str(handle)].append(
            {"index": index, "record": record, "geometry": geometry}
        )

    if invalid_rows:
        add_b("declared_field_type_or_presence_invalid", ("ratio", "reference"), {"rows": invalid_rows})
    for row in geometry_mismatches:
        add_b("declared_field_geometry_contradiction", ("ratio", "reference"), row)
    for row in grid_display:
        add_b("grid_positive_display_contradiction", ("ratio", "reference"), row)
    for row in annotation_rows:
        add_b("unregistered_annotation_scale_residual", ("reference",), row)
    for row in ratio_missing:
        add_b("ratio_missing_or_ambiguous_declaration", ("ratio", "reference"), row)

    ratio_reps: list[dict[str, Any]] = []
    span_reps: list[dict[str, Any]] = []
    ratio_conflicts: list[dict[str, Any]] = []
    span_conflicts: list[dict[str, Any]] = []
    type_conflicts: list[dict[str, Any]] = []

    for handle, rows in sorted(by_handle.items()):
        types = sorted({str(row["record"].get("anchor_type", "")).upper() for row in rows})
        if len(types) > 1:
            detail = {"handle": handle, "anchor_types": types, "record_count": len(rows)}
            type_conflicts.append(detail)
            add_b("source_handle_type_conflict", ("ratio", "reference"), detail)

        span_values = [float(row["geometry"]) for row in rows]
        if span_values and not all(
            math.isclose(
                value,
                span_values[0],
                rel_tol=GEOMETRY_REL_TOLERANCE,
                abs_tol=GEOMETRY_ABS_TOLERANCE,
            )
            for value in span_values[1:]
        ):
            detail = {
                "handle": handle,
                "record_count": len(rows),
                "geometry_span_min": min(span_values),
                "geometry_span_max": max(span_values),
                "log_span_spread_tau": (
                    math.log(max(span_values) / min(span_values)) / RANSAC_LOG_TOLERANCE
                ),
            }
            span_conflicts.append(detail)
            add_b("source_handle_span_conflict", ("reference",), detail)
        elif rows:
            span_reps.append(_span_entry(rows[0]["record"], rows[0]["geometry"]))

        role_rows = [
            row
            for row in rows
            if str(row["record"].get("anchor_type", "")).upper() in ("DIM", "TEXT")
        ]
        entries = [_ratio_entry(row["record"], row["geometry"]) for row in role_rows]
        usable = [entry for entry in entries if entry is not None]
        if not role_rows:
            continue
        if len(usable) != len(role_rows):
            continue
        spaces = sorted({str(entry["ratio_space"]) for entry in usable})
        values = [float(entry["log_ratio"]) for entry in usable]
        if len(spaces) != 1 or max(values) - min(values) > (
            HONEST_RATIO_ROUNDOFF_MAX_TAU * RANSAC_LOG_TOLERANCE + 1e-15
        ):
            detail = {
                "handle": handle,
                "record_count": len(role_rows),
                "ratio_spaces": spaces,
                "log_ratio_min": min(values),
                "log_ratio_max": max(values),
                "spread_tau": (max(values) - min(values)) / RANSAC_LOG_TOLERANCE,
            }
            ratio_conflicts.append(detail)
            add_b("source_handle_ratio_conflict", ("ratio", "reference"), detail)
        else:
            representative = copy.deepcopy(usable[0])
            representative["weight"] = max(float(entry["weight"]) for entry in usable)
            representative["source_record_count"] = len(usable)
            ratio_reps.append(representative)

    spaces_present = sorted({str(row["ratio_space"]) for row in ratio_reps})
    if len(spaces_present) > 1:
        add_b(
            "mixed_estimator_ratio_space_trace",
            ("ratio", "reference"),
            {
                "ratio_spaces": spaces_present,
                "handles_by_space": {
                    space: sorted(
                        str(row["handle"])
                        for row in ratio_reps
                        if str(row["ratio_space"]) == space
                    )
                    for space in spaces_present
                },
            },
        )

    ratio_consensus, _ratio_inliers = _select_consensus(
        ratio_reps, "log_ratio", spaces=True
    )
    ratio_distances: dict[str, float] = {}
    selected_ratio_space = None
    ratio_location = None
    grid_present = bool(ratio_absent_grids)
    if ratio_consensus is not None:
        selected_ratio_space = str(ratio_consensus["space"])
        ratio_location = float(ratio_consensus["location"])
        for row in ratio_reps:
            handle = str(row["handle"])
            if str(row["ratio_space"]) != selected_ratio_space:
                continue
            distance_tau = abs(float(row["log_ratio"]) - ratio_location) / RANSAC_LOG_TOLERANCE
            ratio_distances[handle] = float(distance_tau)
            measurement = {
                "handle": handle,
                "distance_tau": float(distance_tau),
                "ratio_space": selected_ratio_space,
                "log_ratio": float(row["log_ratio"]),
                "consensus_location": ratio_location,
            }
            if distance_tau <= HONEST_RATIO_ROUNDOFF_MAX_TAU + 1e-12:
                continue
            if distance_tau >= SEVERE_DISTANCE_TAU - 1e-12:
                add_b("severe_distance_ratio", ("ratio", "reference"), measurement)
            elif selected_ratio_space != "z_mm":
                add_b(
                    "unregistered_or_envelope_exceeding_ratio_residual",
                    ("ratio", "reference"),
                    {**measurement, "reason": "z_raw_residual_not_in_sealed_Tier_A_list"},
                )
            elif grid_present and distance_tau <= O2_TYPE_TO_GRID_MAX_TAU + 1e-12:
                add_a(
                    "O2_class_type_to_grid_display_residual",
                    ("ratio", "reference"),
                    measurement,
                    limit_tau=O2_TYPE_TO_GRID_MAX_TAU,
                    envelope_entry="accepted_l1e_residual_examples_with_O2_precedent.W000004",
                )
            elif grid_present:
                add_b(
                    "unregistered_or_envelope_exceeding_ratio_residual",
                    ("ratio", "reference"),
                    {
                        **measurement,
                        "reason": "ratio_absent_GRID_with_residual_above_W000004_limit",
                        "type_to_grid_limit_tau": O2_TYPE_TO_GRID_MAX_TAU,
                    },
                )
            elif distance_tau <= O2_STALE_MAX_TAU + 1e-12:
                add_a(
                    "O2_class_moderate_display_stale",
                    ("ratio", "reference"),
                    measurement,
                    limit_tau=O2_STALE_MAX_TAU,
                    envelope_entry="observed_signal_kinds_and_numeric_limits.O2_class_moderate_display_stale",
                )
            else:
                add_b(
                    "unregistered_or_envelope_exceeding_ratio_residual",
                    ("ratio", "reference"),
                    {
                        **measurement,
                        "reason": "above_O2_stale_limit_below_severe_boundary",
                        "O2_stale_limit_tau": O2_STALE_MAX_TAU,
                    },
                )

    span_consensus, _span_inliers = _select_consensus(
        span_reps, "log_span", spaces=False
    )
    span_distances: dict[str, float] = {}
    span_location = None
    if span_consensus is not None:
        span_location = float(span_consensus["location"])
        for row in span_reps:
            handle = str(row["handle"])
            distance_tau = abs(float(row["log_span"]) - span_location) / RANSAC_LOG_TOLERANCE
            span_distances[handle] = float(distance_tau)
            if distance_tau <= HONEST_RATIO_ROUNDOFF_MAX_TAU + 1e-12:
                continue
            measurement = {
                "handle": handle,
                "distance_tau": float(distance_tau),
                "log_span": float(row["log_span"]),
                "consensus_location": span_location,
            }
            if distance_tau >= SEVERE_DISTANCE_TAU - 1e-12:
                add_b("severe_distance_span", ("reference",), measurement)
            else:
                add_b(
                    "unregistered_or_envelope_exceeding_span_residual",
                    ("reference",),
                    measurement,
                )

    rule_measurements: dict[str, list[dict[str, Any]]] = defaultdict(list)
    rule_measurements["declared_field_inventory"].append(
        {
            "record_count": len(surface),
            "field_presence_counts": dict(sorted(field_counts.items())),
            "minimum_field_presence_counts": dict(minimum_presence),
            "future_or_extension_fields": sorted(
                set(field_counts) - set(CURRENT_MINIMUM_DECLARED_FIELDS)
            ),
        }
    )
    rule_measurements["declared_field_type_and_presence"].extend(invalid_rows)
    rule_measurements["raw_span_equals_euclidean_geometry"].extend(geometry_mismatches)
    rule_measurements["source_handle_type_conflict"].extend(type_conflicts)
    rule_measurements["source_handle_ratio_conflict"].extend(ratio_conflicts)
    rule_measurements["source_handle_span_conflict"].extend(span_conflicts)
    rule_measurements["ratio_missing_or_ambiguous_declaration"].extend(ratio_missing)
    rule_measurements["grid_positive_display_contradiction"].extend(grid_display)
    rule_measurements["annotation_scale_unregistered"].extend(annotation_rows)
    if len(spaces_present) > 1:
        rule_measurements["mixed_estimator_ratio_space_trace"].append(
            {"ratio_spaces": spaces_present}
        )
    rule_measurements["ratio_absent_GRID_neutrality"].extend(
        {"handle": handle} for handle in sorted(set(ratio_absent_grids))
    )
    for signal in tier_a + tier_b:
        kind = str(signal["signal_kind"])
        mapping = {
            "severe_distance_ratio": "ratio_severe_distance",
            "severe_distance_span": "span_severe_distance",
            "unregistered_or_envelope_exceeding_ratio_residual": "ratio_unregistered_or_envelope_exceeding_residual",
            "unregistered_or_envelope_exceeding_span_residual": "span_unregistered_or_envelope_exceeding_residual",
        }
        rule_measurements[mapping.get(kind, kind)].append(copy.deepcopy(signal["measurement"]))

    roundoff_rows = [
        {"handle": handle, "distance_tau": distance}
        for handle, distance in sorted(ratio_distances.items())
        if 0.0 < distance <= HONEST_RATIO_ROUNDOFF_MAX_TAU + 1e-12
    ]
    rule_measurements["honest_corpus_coherent_ratio_roundoff"].extend(roundoff_rows)

    executed_rules = [
        {
            "rule_id": rule_id,
            "observed_count": len(rule_measurements.get(rule_id, [])),
            "measurements": list(rule_measurements.get(rule_id, [])),
        }
        for rule_id in DETECTION_RULE_ORDER
    ]
    hard_ratio = any("ratio" in row["affected_paths"] for row in tier_b)
    hard_reference = any("reference" in row["affected_paths"] for row in tier_b)
    tier_a_factor_ratio = math.prod(
        1.0 - float(row["penalty_floor"])
        for row in tier_a
        if "ratio" in row["affected_paths"]
    )
    tier_a_factor_reference = math.prod(
        1.0 - float(row["penalty_floor"])
        for row in tier_a
        if "reference" in row["affected_paths"]
    )
    ratio_clean_handles = sorted(
        handle
        for handle, distance in ratio_distances.items()
        if distance <= HONEST_RATIO_ROUNDOFF_MAX_TAU + 1e-12
    )
    span_clean_handles = sorted(
        handle
        for handle, distance in span_distances.items()
        if distance <= HONEST_RATIO_ROUNDOFF_MAX_TAU + 1e-12
    )
    return {
        "surface_digest": _canonical_digest(surface),
        "record_count": len(surface),
        "declared_field_inventory": dict(sorted(field_counts.items())),
        "current_minimum_field_presence": dict(minimum_presence),
        "future_or_extension_fields": sorted(
            set(field_counts) - set(CURRENT_MINIMUM_DECLARED_FIELDS)
        ),
        "uncovered_declared_field_count": 0,
        "executed_rule_order": list(DETECTION_RULE_ORDER),
        "executed_rules": executed_rules,
        "rule_counts": {
            row["rule_id"]: int(row["observed_count"]) for row in executed_rules
        },
        "tier_A_signals": tier_a,
        "tier_B_signals": tier_b,
        "tier_A_signal_count": len(tier_a),
        "tier_B_signal_count": len(tier_b),
        "residual_suspicion_count": len(tier_a) + len(tier_b),
        "hard_paths": {"ratio": hard_ratio, "reference": hard_reference},
        "tier_A_attenuation": {
            "ratio_factor": float(tier_a_factor_ratio),
            "reference_factor": float(tier_a_factor_reference),
            "aggregation": "product_of_candidate_count_independent_per_signal_factors",
        },
        "selected_ratio_space": selected_ratio_space,
        "ratio_consensus_location": ratio_location,
        "span_consensus_location": span_location,
        "ratio_distances_tau": dict(sorted(ratio_distances.items())),
        "span_distances_tau": dict(sorted(span_distances.items())),
        "ratio_clean_support_handles": ratio_clean_handles,
        "span_clean_support_handles": span_clean_handles,
        "ratio_absent_neutral_handles": sorted(set(ratio_absent_grids)),
        "_surface": surface,
        "_ratio_representatives": ratio_reps,
        "_span_representatives": span_reps,
    }


def _public_analysis(analysis: Mapping[str, Any]) -> dict[str, Any]:
    return {
        key: copy.deepcopy(value)
        for key, value in analysis.items()
        if not str(key).startswith("_")
    }


def suspicion_analysis(
    raw_anchors: Sequence[Mapping[str, Any]],
) -> dict[str, Any]:
    return _public_analysis(analyze_frozen_surface(raw_anchors))


def _support_policy(
    representatives: Sequence[Mapping[str, Any]],
    value_key: str,
    clean_handles: Sequence[str],
    attenuation_factor: float,
) -> dict[str, Any] | None:
    clean = [
        dict(row) for row in representatives if str(row["handle"]) in set(clean_handles)
    ]
    if not clean:
        return None
    values = [float(row[value_key]) for row in clean]
    weights = [float(row.get("weight", 1.0)) for row in clean]
    location = huber_location(values, weights)
    log_mad = weighted_log_mad(values, weights, location)
    residual = math.exp(-float(log_mad) / RANSAC_LOG_TOLERANCE)
    if math.isclose(residual, 1.0, rel_tol=0.0, abs_tol=1e-12):
        residual = 1.0
    score = float(residual * float(attenuation_factor))
    if math.isclose(score, 0.75, rel_tol=0.0, abs_tol=1e-12):
        score = 0.75
    points = {str(row["handle"]): midpoint(row) for row in clean}
    spatial_bins = len({(round(x, 9), round(y, 9)) for x, y in points.values()})
    candidate_handles = sorted({str(row["handle"]) for row in representatives})
    support_handles = sorted({str(row["handle"]) for row in clean})
    return {
        "location": float(location),
        "log_mad": float(log_mad),
        "score": score,
        "n_independent": len(support_handles),
        "n_candidate_handles": len(candidate_handles),
        "n_spatial_bins": spatial_bins,
        "n_candidate_spatial_bins": spatial_bins,
        "candidate_weight": float(len(candidate_handles)),
        "inlier_weight": float(len(support_handles)),
        "consensus_fraction": (
            0.0 if not candidate_handles else len(support_handles) / len(candidate_handles)
        ),
        "residual_factor": float(residual),
        "per_signal_attenuation_factor": float(attenuation_factor),
        "confidence_inlier_handles": support_handles,
        "candidate_handles": candidate_handles,
        "continuous_formula": NON_DILUTION_FORMULA,
        "candidate_count_used_in_suspicion_penalty": False,
    }


def _status(estimate: float | None, policy: Mapping[str, Any] | None) -> str:
    if estimate is None or policy is None:
        return "NONE"
    if int(policy["n_independent"]) < MIN_HANDLES_NON_NONE:
        return "NONE"
    if float(policy["score"]) <= 1e-15:
        return "NONE"
    high = (
        int(policy["n_independent"]) >= MIN_HANDLES_HIGH
        and float(policy["log_mad"]) <= RANSAC_LOG_TOLERANCE
        and float(policy["score"]) >= HIGH_CONFIDENCE_THRESHOLD - 1e-12
    )
    return "HIGH" if high else "LOW"


def fit_anchor_model(raw_anchors: Sequence[Mapping[str, Any]]) -> dict[str, Any]:
    analysis = analyze_frozen_surface(raw_anchors)
    prepared, prepare_audit = prepare_anchors(raw_anchors)

    ratio_policy = _support_policy(
        analysis["_ratio_representatives"],
        "log_ratio",
        analysis["ratio_clean_support_handles"],
        analysis["tier_A_attenuation"]["ratio_factor"],
    )
    if analysis["hard_paths"]["ratio"] or ratio_policy is None or int(ratio_policy["n_independent"]) < MIN_HANDLES_NON_NONE:
        scale_estimate = None
        unit_status = "NONE"
        ratio_policy_public = copy.deepcopy(ratio_policy)
        if ratio_policy_public is not None:
            ratio_policy_public["score"] = 0.0
            ratio_policy_public["hard_block_applied"] = bool(analysis["hard_paths"]["ratio"])
    else:
        scale_estimate = math.exp(float(ratio_policy["location"]))
        unit_status = _status(scale_estimate, ratio_policy)
        ratio_policy_public = copy.deepcopy(ratio_policy)
        ratio_policy_public["hard_block_applied"] = False

    ratio_space = analysis["selected_ratio_space"]
    if scale_estimate is not None and ratio_space == "z_mm":
        physical_unit = "MM"
        mm_per_raw = scale_estimate
    else:
        physical_unit = "UNKNOWN"
        mm_per_raw = None

    reference_attenuation = float(
        analysis["tier_A_attenuation"]["reference_factor"]
    )
    reference_policy = _support_policy(
        analysis["_span_representatives"],
        "log_span",
        analysis["span_clean_support_handles"],
        reference_attenuation,
    )
    if analysis["hard_paths"]["reference"] or reference_policy is None or int(reference_policy["n_independent"]) < MIN_HANDLES_NON_NONE:
        reference_span = None
        reference_status = "NONE"
        reference_policy_public = copy.deepcopy(reference_policy)
        if reference_policy_public is not None:
            reference_policy_public["score"] = 0.0
            reference_policy_public["hard_block_applied"] = bool(
                analysis["hard_paths"]["reference"]
            )
    else:
        reference_span = math.exp(float(reference_policy["location"]))
        reference_status = _status(reference_span, reference_policy)
        reference_policy_public = copy.deepcopy(reference_policy)
        reference_policy_public["hard_block_applied"] = False

    ratio_score = 0.0 if ratio_policy_public is None else float(ratio_policy_public["score"])
    reference_score = (
        0.0 if reference_policy_public is None else float(reference_policy_public["score"])
    )
    ratio_candidates = sorted(
        {str(row["handle"]) for row in analysis["_ratio_representatives"]}
    )
    ratio_inliers = [] if ratio_policy is None else list(ratio_policy["confidence_inlier_handles"])
    span_candidates = sorted(
        {str(row["handle"]) for row in analysis["_span_representatives"]}
    )
    span_inliers = [] if reference_policy is None else list(reference_policy["confidence_inlier_handles"])
    source_diversity = sorted(
        {
            str(anchor.get("anchor_type", "")).upper()
            for anchor in raw_anchors
            if isinstance(anchor, Mapping)
        }
    )
    return {
        "status": reference_status,
        "unit_status": unit_status,
        "reference_status": reference_status,
        "display_per_raw": scale_estimate,
        "physical_unit": physical_unit,
        "mm_per_raw": mm_per_raw,
        "consensus_weight": None
        if ratio_policy is None
        else float(ratio_policy["consensus_fraction"]),
        "log_mad": None if ratio_policy is None else float(ratio_policy["log_mad"]),
        "n_independent": 0 if ratio_policy is None else int(ratio_policy["n_independent"]),
        "n_candidate_handles": 0 if ratio_policy is None else int(ratio_policy["n_candidate_handles"]),
        "n_spatial_bins": 0 if ratio_policy is None else int(ratio_policy["n_spatial_bins"]),
        "n_candidate_spatial_bins": 0 if ratio_policy is None else int(ratio_policy["n_candidate_spatial_bins"]),
        "confidence_score": ratio_score,
        "source_diversity": source_diversity,
        "reference_span": reference_span,
        "reference_consensus_weight": None
        if reference_policy is None
        else float(reference_policy["consensus_fraction"]),
        "reference_log_mad": None
        if reference_policy is None
        else float(reference_policy["log_mad"]),
        "reference_n_independent": 0
        if reference_policy is None
        else int(reference_policy["n_independent"]),
        "reference_n_candidate_handles": 0
        if reference_policy is None
        else int(reference_policy["n_candidate_handles"]),
        "reference_n_spatial_bins": 0
        if reference_policy is None
        else int(reference_policy["n_spatial_bins"]),
        "reference_n_candidate_spatial_bins": 0
        if reference_policy is None
        else int(reference_policy["n_candidate_spatial_bins"]),
        "reference_confidence_score": reference_score,
        "provenance": {
            **prepare_audit,
            "revision": REVISION,
            "frozen_surface_digest": analysis["surface_digest"],
            "frozen_declared_field_inventory": analysis["declared_field_inventory"],
            "frozen_uncovered_declared_field_count": analysis[
                "uncovered_declared_field_count"
            ],
            "ratio_mode_space": ratio_space,
            "ratio_inlier_handles": ratio_inliers,
            "ratio_outlier_handles": sorted(set(ratio_candidates) - set(ratio_inliers)),
            "ratio_attenuated_handles": sorted(
                {
                    str(row["measurement"].get("handle"))
                    for row in analysis["tier_A_signals"] + analysis["tier_B_signals"]
                    if "ratio" in row["affected_paths"] and row["measurement"].get("handle") is not None
                }
            ),
            "ratio_absent_neutral_handles": analysis["ratio_absent_neutral_handles"],
            "reference_inlier_handles": span_inliers,
            "reference_confidence_inlier_handles": span_inliers,
            "reference_outlier_handles": sorted(set(span_candidates) - set(span_inliers)),
            "reference_label_policy": "label_free_span_space",
            "independence_key": "unique_source_handle",
            "minimum_handles_non_none": MIN_HANDLES_NON_NONE,
            "minimum_handles_high": MIN_HANDLES_HIGH,
            "suspicious_evidence_role": "denominator_only_never_numerator_or_estimate",
            "two_tier_suspicion": _public_analysis(analysis),
            "denominator_policy": {
                "ratio": ratio_policy_public,
                "reference": reference_policy_public,
                "candidate_count_mean_penalty_used": False,
                "ratio_absent_handles_in_ratio_mean": 0,
                "subset_basis": "source_handle_sets",
            },
            "continuous_attenuation": {
                "formula": NON_DILUTION_FORMULA,
                "boundary_behavior": BOUNDARY_BEHAVIOR,
            },
        },
    }


def build_honest_witness(
    raw_anchors: Sequence[Mapping[str, Any]],
) -> dict[str, Any] | None:
    """Generate an invariant-checked honest scene from a semantic spec.

    The witness is not a JSON round-trip copy: raw_span is regenerated from the
    declared geometry by this predeclared generator, and every other declared
    field is an explicit typed generator parameter.
    """
    analysis = analyze_frozen_surface(raw_anchors)
    if analysis["tier_B_signal_count"]:
        return None
    surface = analysis["_surface"]
    spec_records: list[dict[str, Any]] = []
    generated: list[dict[str, Any]] = []
    for ordinal, record in enumerate(surface):
        geometry = _geometry_span(record)
        raw_span = _finite(record.get("raw_span"))
        if geometry is None or raw_span is None:
            return None
        parameters = {
            key: copy.deepcopy(value)
            for key, value in record.items()
            if key != "raw_span"
        }
        rebuilt = copy.deepcopy(parameters)
        rebuilt["raw_span"] = float(geometry)
        spec_records.append(
            {
                "ordinal": ordinal,
                "typed_declared_parameters_except_dependent_raw_span": parameters,
                "dependent_rule": "raw_span=EuclideanDistance(p0,p1)",
                "generated_raw_span": float(geometry),
            }
        )
        generated.append(rebuilt)
    post_serialized = canonical_bytes(surface).decode("utf-8")
    generated_serialized = canonical_bytes(generated).decode("utf-8")
    if generated_serialized != post_serialized:
        return None
    spec = {
        "generator_id": "honest_declared_anchor_generator_v1",
        "surface_class": "clean" if not analysis["tier_A_signals"] else "sealed_Tier_A",
        "records": spec_records,
        "admitted_envelope_entries": [
            {
                "signal_kind": row["signal_kind"],
                "sealed_envelope_entry": row["sealed_envelope_entry"],
                "sealed_limit_tau": row["sealed_limit_tau"],
                "observed_distance_tau": row["measurement"]["distance_tau"],
            }
            for row in analysis["tier_A_signals"]
        ],
    }
    spec_digest = _canonical_digest(spec)
    return {
        "witness_scene_identifier": f"HONEST_SPEC::{spec_digest}",
        "honest_generation_spec": spec,
        "honest_generation_spec_digest": spec_digest,
        "witness_surface": generated,
        "witness_serialization": generated_serialized,
        "witness_serialization_sha256": hashlib.sha256(
            generated_serialized.encode("utf-8")
        ).hexdigest(),
        "analysis": _public_analysis(analysis),
    }


def anchor_artifact_from_scene(scene: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "artifact_schema": "ariadne.e2.feyerabend_c1.anchor_artifact.v5",
        "model": fit_anchor_model(copy.deepcopy(scene["anchors"])),
    }


def evaluate_scene(scene: Mapping[str, Any]) -> dict[str, Any]:
    artifact_before = anchor_artifact_from_scene(scene)
    model = artifact_before["model"]
    truth_scale = float(scene["truth_unit_scale"])
    estimate = model["display_per_raw"]
    permuted = permute_pair_labels(scene)
    artifact_after = anchor_artifact_from_scene(permuted)
    before_digest = canonical_sha256(artifact_before)
    after_digest = canonical_sha256(artifact_after)
    truth_before_digest = canonical_sha256(scene.get("truth_pairs", []))
    truth_after_digest = canonical_sha256(permuted.get("truth_pairs", []))

    corruption_rows: dict[str, Any] = {}
    for kind in CORRUPTIONS:
        corrupted_anchors = apply_corruption(
            scene["anchors"], kind, str(scene["base_scene_id"])
        )
        corrupted_model = fit_anchor_model(corrupted_anchors)
        corrupted_estimate = corrupted_model["display_per_raw"]
        same_estimate = (
            estimate is None
            and corrupted_estimate is None
            or estimate is not None
            and corrupted_estimate is not None
            and math.isclose(
                float(estimate),
                float(corrupted_estimate),
                rel_tol=1e-12,
                abs_tol=1e-15,
            )
        )
        corruption_rows[kind] = {
            "status_before": model["status"],
            "status_after": corrupted_model["status"],
            "unit_status_before": model["unit_status"],
            "unit_status_after": corrupted_model["unit_status"],
            "reference_status_before": model["reference_status"],
            "reference_status_after": corrupted_model["reference_status"],
            "physical_unit_before": model["physical_unit"],
            "physical_unit_after": corrupted_model["physical_unit"],
            "scale_estimate_before": estimate,
            "scale_estimate_after": corrupted_estimate,
            "scale_estimate_unchanged": same_estimate,
            "relative_error_after": relative_error(corrupted_estimate, truth_scale),
            "e_s_after": log_error(corrupted_estimate, truth_scale),
            "confidence_score_before": model["confidence_score"],
            "confidence_score_after": corrupted_model["confidence_score"],
            "reference_confidence_score_before": model[
                "reference_confidence_score"
            ],
            "reference_confidence_score_after": corrupted_model[
                "reference_confidence_score"
            ],
            "reference_n_independent_before": model["reference_n_independent"],
            "reference_n_independent_after": corrupted_model[
                "reference_n_independent"
            ],
            "reference_n_spatial_bins_before": model["reference_n_spatial_bins"],
            "reference_n_spatial_bins_after": corrupted_model[
                "reference_n_spatial_bins"
            ],
            "artifact_digest": canonical_sha256(
                {
                    "artifact_schema": artifact_before["artifact_schema"],
                    "model": corrupted_model,
                }
            ),
            "input_anchor_count_after": len(corrupted_anchors),
        }

    score = float(model["confidence_score"])
    return {
        "input_file": str(scene.get("_input_file", "")),
        "scene_id": scene["scene_id"],
        "base_scene_id": scene["base_scene_id"],
        "seed": int(scene["seed"]),
        "scale_kappa": float(scene["scale_kappa"]),
        "truth_unit_scale": truth_scale,
        "input_anchor_count": len(scene["anchors"]),
        "input_anchor_types": sorted(
            {str(anchor.get("anchor_type")) for anchor in scene["anchors"]}
        ),
        "scale_estimate": estimate,
        "e_s": log_error(estimate, truth_scale),
        "relative_error": relative_error(estimate, truth_scale),
        "status": model["status"],
        "unit_status": model["unit_status"],
        "reference_status": model["reference_status"],
        "confidence_score": score,
        "confidence_score_bin": score_bin_for(score),
        "physical_unit": model["physical_unit"],
        "anchor_model": model,
        "assigned_corruption": assigned_corruption(str(scene["base_scene_id"])),
        "corruption_diagnostics": corruption_rows,
        "pair_label_permutation": {
            "truth_label_digest_before": truth_before_digest,
            "truth_label_digest_after": truth_after_digest,
            "truth_label_input_changed": truth_before_digest != truth_after_digest,
            "anchor_artifact_digest_before": before_digest,
            "anchor_artifact_digest_after": after_digest,
            "anchor_artifact_digest_equal": before_digest == after_digest,
        },
    }


def _snapshot(model: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "confidence_score": float(model["confidence_score"]),
        "reference_confidence_score": float(model["reference_confidence_score"]),
        "status": str(model["status"]),
        "unit_status": str(model["unit_status"]),
        "reference_status": str(model["reference_status"]),
        "display_per_raw": model["display_per_raw"],
        "mm_per_raw": model["mm_per_raw"],
        "consensus_weight": model["consensus_weight"],
        "reference_consensus_weight": model["reference_consensus_weight"],
        "n_independent": int(model["n_independent"]),
        "n_candidate_handles": int(model["n_candidate_handles"]),
        "n_spatial_bins": int(model["n_spatial_bins"]),
        "reference_n_independent": int(model["reference_n_independent"]),
        "reference_n_candidate_handles": int(model["reference_n_candidate_handles"]),
        "reference_n_spatial_bins": int(model["reference_n_spatial_bins"]),
        "ratio_inlier_handles": list(model["provenance"]["ratio_inlier_handles"]),
        "ratio_outlier_handles": list(model["provenance"]["ratio_outlier_handles"]),
        "ratio_attenuated_handles": list(model["provenance"]["ratio_attenuated_handles"]),
        "ratio_absent_neutral_handles": list(
            model["provenance"]["ratio_absent_neutral_handles"]
        ),
        "reference_inlier_handles": list(
            model["provenance"]["reference_inlier_handles"]
        ),
        "reference_outlier_handles": list(
            model["provenance"]["reference_outlier_handles"]
        ),
        "tier_A_signal_count": int(
            model["provenance"]["two_tier_suspicion"]["tier_A_signal_count"]
        ),
        "tier_B_signal_count": int(
            model["provenance"]["two_tier_suspicion"]["tier_B_signal_count"]
        ),
    }


def _increases(before: Mapping[str, Any], after: Mapping[str, Any]) -> dict[str, bool]:
    return V4._increases(before, after)


def run_selftests(stream: io.TextIOBase) -> dict[str, Any]:
    observations: list[dict[str, Any]] = []

    def observe(identifier: str, value: bool, detail: Mapping[str, Any]) -> None:
        row = {"id": identifier, "observed": bool(value), "detail": dict(detail)}
        observations.append(row)
        print(json.dumps(row, ensure_ascii=False, sort_keys=True), file=stream)
        if not value:
            raise AssertionError(identifier)

    clean_anchors = exact_fixture()
    clean = fit_anchor_model(clean_anchors)
    observe(
        "clean_exact_model",
        clean["unit_status"] == "HIGH"
        and math.isclose(float(clean["display_per_raw"]), 2.5, rel_tol=1e-12),
        {"unit_status": clean["unit_status"], "estimate": clean["display_per_raw"]},
    )
    forged = copy.deepcopy(clean_anchors[:3])
    forged[-1]["p1"] = [forged[-1]["p0"][0] + 300.0, forged[-1]["p0"][1]]
    forged[-1]["display_value"] = 750.0
    forged_model = fit_anchor_model(forged)
    forged_analysis = suspicion_analysis(forged)
    observe(
        "precanonical_declared_geometry_hard_block",
        forged_model["confidence_score"] == 0.0
        and forged_model["reference_confidence_score"] == 0.0
        and forged_model["unit_status"] == "NONE"
        and forged_analysis["rule_counts"]["raw_span_equals_euclidean_geometry"] == 1,
        {
            "confidence": forged_model["confidence_score"],
            "reference": forged_model["reference_confidence_score"],
            "mismatch_count": forged_analysis["rule_counts"]["raw_span_equals_euclidean_geometry"],
        },
    )
    grids = [
        _make_anchor(f"GRID_{index}", 100.0, None, 1000.0 * index, 1000.0, anchor_type="GRID")
        for index in range(5)
    ]
    ref_before = fit_anchor_model(clean_anchors[:3])
    ref_after = fit_anchor_model(clean_anchors[:3] + grids)
    observe(
        "ratio_absent_grid_neutral",
        math.isclose(
            float(ref_before["reference_confidence_score"]),
            float(ref_after["reference_confidence_score"]),
            rel_tol=0.0,
            abs_tol=1e-15,
        )
        and ref_before["reference_status"] == ref_after["reference_status"],
        {
            "before": ref_before["reference_confidence_score"],
            "after": ref_after["reference_confidence_score"],
            "status_before": ref_before["reference_status"],
            "status_after": ref_after["reference_status"],
        },
    )
    tau = RANSAC_LOG_TOLERANCE
    base = clean_anchors[:3]
    edge_lo = copy.deepcopy(base)
    edge_hi = copy.deepcopy(base)
    edge_lo.append(_make_anchor("EDGE", 100.0, 250.0 * math.exp((1.0 - 1e-9) * tau), *POSITIONS[3]))
    edge_hi.append(_make_anchor("EDGE", 100.0, 250.0 * math.exp((1.0 + 1e-9) * tau), *POSITIONS[3]))
    low_score = fit_anchor_model(edge_lo)["confidence_score"]
    high_score = fit_anchor_model(edge_hi)["confidence_score"]
    observe(
        "tau_boundary_continuous",
        abs(float(low_score) - float(high_score)) < 1e-7,
        {"below": low_score, "above": high_score, "absolute_delta": abs(low_score - high_score)},
    )
    suspicious = copy.deepcopy(base)
    suspicious.append(_make_anchor("STALE", 100.0, 250.0 * math.exp(2.0 * tau), *POSITIONS[3]))
    clean_additions = [
        _make_anchor(f"N{index}", 100.0, 250.0, 20000.0 + 500.0 * index, 30000.0)
        for index in range(40)
    ]
    score_n0 = fit_anchor_model(suspicious)["confidence_score"]
    score_n40 = fit_anchor_model(suspicious + clean_additions)["confidence_score"]
    observe(
        "fixed_s_non_dilution",
        math.isclose(float(score_n0), float(score_n40), rel_tol=0.0, abs_tol=1e-15),
        {"N0": score_n0, "N40": score_n40, "absolute_delta": abs(score_n0 - score_n40)},
    )
    return {
        "observed_count": sum(int(row["observed"]) for row in observations),
        "total": len(observations),
        "observations": observations,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--selftest", action="store_true")
    arguments = parser.parse_args(argv)
    if not arguments.selftest:
        parser.error("only --selftest is supported; use loop_l1f.py for the full run")
    stream = io.StringIO()
    result = run_selftests(stream)
    print(stream.getvalue(), end="")
    return 0 if result["observed_count"] == result["total"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
